[load_balancers]
rke2-lb-01 ansible_host=192.168.56.100 node_ip=192.168.56.100

[masters]
rke2-master-01 ansible_host=192.168.56.101 node_ip=192.168.56.101

[workers]
rke2-worker-01 ansible_host=192.168.56.102 node_ip=192.168.56.102
rke2-worker-02 ansible_host=192.168.56.103 node_ip=192.168.56.103

[rke2_cluster:children]
masters
workers

[all_lab:children]
load_balancers
rke2_cluster

[all_lab:vars]
ansible_user=mnhduc
ansible_become=true
ansible_python_interpreter=/usr/bin/python3
