[masters]
rke2-master-01 ansible_host=192.168.56.101 node_ip=192.168.56.101

[workers]
rke2-worker-01 ansible_host=192.168.56.102 node_ip=192.168.56.102
rke2-worker-02 ansible_host=192.168.56.103 node_ip=192.168.56.103

[rke2_cluster:children]
masters
workers

[rke2_cluster:vars]
ansible_user=mnhduc
ansible_become=true
ansible_python_interpreter=/usr/bin/python3

rke2_master_ip=192.168.56.101
rke2_master_hostname=rke2-master-01
